module.exports = Object.freeze({
    SOFTWARE_ENGINEER: 'SOFTWARE_ENGINEER',
    SOFTWARE_TEST_ENGINEER: 'SOFTWARE_TEST_ENGINEER',
    SOFTWARE_TEST_AUTOMATION_ENGINEER: 'SOFTWARE_TEST_AUTOMATION_ENGINEER',
    PROJECT_MANAGER: 'PROJECT_MANAGER',
    RESOURCE_MANAGER: 'RESOURCE_MANAGER'
});
